import BitFoundation
import CryptoKit
import Foundation
import XCTest

@testable import bitchat

/// Frozen byte contracts generated by the original Bitchat implementation at
/// commit 1f59e814f90c3f489f48d68262cb1bf640bf6181. Expected values are kept
/// independent of the production encoders so protocol drift fails loudly.
final class BitchatSecurityWireCompatibilityTests: XCTestCase {
    private let key = SymmetricKey(data: Data((0..<32).map(UInt8.init)))
    private let transportFrameHex =
        "000000007ad13652c587d2fc64082e0482357fd73f85d69024f3baf5fa6af063b55967"

    func test_noiseProtocolAndTypeAssignmentsMatchBitchat() {
        XCTAssertEqual(
            NoiseProtocolName(pattern: NoisePattern.XX.patternName).fullName,
            "Noise_XX_25519_ChaChaPoly_SHA256"
        )
        XCTAssertEqual(MessageType.noiseHandshake.rawValue, 0x10)
        XCTAssertEqual(MessageType.noiseEncrypted.rawValue, 0x11)
        XCTAssertEqual(NoisePayloadType.verifyChallenge.rawValue, 0x10)
        XCTAssertEqual(NoisePayloadType.verifyResponse.rawValue, 0x11)
        XCTAssertEqual(NoisePayloadType.authenticatedPeerState.rawValue, 0x21)
    }

    func test_extractedNonceTransportFrameMatchesBitchat() throws {
        let sender = NoiseCipherState(key: key, useExtractedNonce: true)
        let expected = try XCTUnwrap(Data(hexString: transportFrameHex))

        let encoded = try sender.encrypt(
            plaintext: Data("bitchat-wire-v1".utf8)
        )

        XCTAssertEqual(encoded, expected)
        XCTAssertEqual(encoded.prefix(4), Data([0x00, 0x00, 0x00, 0x00]))

        let receiver = NoiseCipherState(key: key, useExtractedNonce: true)
        XCTAssertEqual(
            try receiver.decrypt(ciphertext: expected),
            Data("bitchat-wire-v1".utf8)
        )
    }

    func test_noiseEncryptedOuterPacketMatchesBitchatBinaryProtocol() throws {
        let frame = try XCTUnwrap(Data(hexString: transportFrameHex))
        let signature = Data((0..<64).map { UInt8(0xA0 + $0) })
        let packet = BitchatPacket(
            type: MessageType.noiseEncrypted.rawValue,
            senderID: try XCTUnwrap(Data(hexString: "0011223344556677")),
            recipientID: try XCTUnwrap(Data(hexString: "8899aabbccddeeff")),
            timestamp: 0x0102_0304_0506_0708,
            payload: frame,
            signature: signature,
            ttl: 5,
            version: 1
        )
        let expected = try XCTUnwrap(Data(hexString:
            "0111050102030405060708030023" +
            "0011223344556677" +
            "8899aabbccddeeff" +
            transportFrameHex +
            "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf" +
            "b0b1b2b3b4b5b6b7b8b9babbbcbdbebf" +
            "c0c1c2c3c4c5c6c7c8c9cacbcccdcecf" +
            "d0d1d2d3d4d5d6d7d8d9dadbdcdddedf"
        ))

        XCTAssertEqual(packet.toBinaryData(padding: false), expected)

        let decoded = try XCTUnwrap(BitchatPacket.from(expected))
        XCTAssertEqual(decoded.version, 1)
        XCTAssertEqual(decoded.type, MessageType.noiseEncrypted.rawValue)
        XCTAssertEqual(decoded.ttl, 5)
        XCTAssertEqual(decoded.timestamp, 0x0102_0304_0506_0708)
        XCTAssertEqual(decoded.senderID, packet.senderID)
        XCTAssertEqual(decoded.recipientID, packet.recipientID)
        XCTAssertEqual(decoded.payload, frame)
        XCTAssertEqual(decoded.signature, signature)
    }
}
